export const TEMPLATE_CATEGORIES = {
    URGENT: '긴박형/불안형',
    EXPERIMENTAL: '실험형/경험형',
    COMPARATIVE: '비교형/분석형',
    AGGRESSIVE: '어그로형/비법형'
};

export const TEMPLATES = [
    // 1. URGENT (Warning/Mistake focus)
    { text: "{topic} 할 때 당신이 몰랐던 {number}가지 충격적인 사실", category: "URGENT" },
    { text: "와.. 이걸 몰라서 {topic} 망쳤구나", category: "URGENT" },
    { text: "설마 아직도 {topic} 이렇게 하고 있지는 않나요?", category: "URGENT" },
    { text: "{benefit} 하려면 지금 당장 버려야 할 {number}가지 습관", category: "URGENT" },
    { text: "{topic} 하는 당신이 반드시 알아야 할 {number}가지", category: "URGENT" },
    { text: "모르면 무조건 손해보는 {topic} 상식", category: "URGENT" },
    { text: "모르면 평생 후회하는 {topic}의 진실", category: "URGENT" },
    { text: "{topic} 하고 싶다면 절대 하면 안되는 {number}가지", category: "URGENT" },
    { text: "대부분의 {target}들이 잘못하고 있는 ‘이것’", category: "URGENT" },
    { text: "대부분의 {target}들이 몰라서 못하는 {topic} {number}가지", category: "URGENT" },
    { text: "{topic} 진심인 사람은 절대 보지마세요", category: "URGENT" },
    { text: "{topic}, 이렇게 하면 절대 안됩니다", category: "URGENT" },
    { text: "{topic}, 이렇게 하면 무조건 망합니다", category: "URGENT" },
    { text: "제발 {topic} 하지 마세요", category: "URGENT" },
    { text: "{target}이라면 {topic} 절대 하지 마세요", category: "URGENT" },
    { text: "{topic} 할 때 모르면 금방 폭망하는 {number}가지", category: "URGENT" },
    { text: "{topic} 하기 전에 안보면 후회할 {number}가지", category: "URGENT" },
    { text: "{topic} 하기 전 무조건 알아야 할 {number}가지", category: "URGENT" },
    { text: "평생 후회하기 전에 점검해야 할 {topic} 체크리스트", category: "URGENT" },
    { text: "{target}라면 주목, 모르면 손해보는 {topic}", category: "URGENT" },
    { text: "{target}라면 하루라도 빨리 시작해야 할 {number}가지", category: "URGENT" },
    { text: "만약 {topic} 하고 싶다면 이것만은 꼭하세요", category: "URGENT" },
    { text: "{target}라면 모르면 안 되는 이것", category: "URGENT" },
    { text: "지금 {target}들이 무조건 알아야 할 {topic}", category: "URGENT" },

    // 2. EXPERIMENTAL (Story/Journey/Experience focus)
    { text: "내가 {topic} 한다면 지금 당장 시작할 {number}가지", category: "EXPERIMENTAL" },
    { text: "한국인이 {topic} 하면 생기는 일", category: "EXPERIMENTAL" },
    { text: "{topic} 했을 때 겪게 되는 충격적인 상황", category: "EXPERIMENTAL" },
    { text: "경력 {number}년차 {authority}가 밝히는 {topic}의 불편한 진실", category: "EXPERIMENTAL" },
    { text: "{number}년 차 {authority} 해보고 느낀 {topic}", category: "EXPERIMENTAL" },
    { text: "{topic} {number}년 하고 미치도록 후회하는 이유", category: "EXPERIMENTAL" },
    { text: "{target}인 내가 {content}하게 된 방법", category: "EXPERIMENTAL" },
    { text: "{target}인 내가 {topic} 시작한 이유", category: "EXPERIMENTAL" },
    { text: "{topic} 초보였던 내가 {benefit} 달성한 비법", category: "EXPERIMENTAL" },
    { text: "{topic}하는 내가 과거로 돌아간다면 무조건 할 {number}가지", category: "EXPERIMENTAL" },
    { text: "{topic}하는 내가 시작할 때 가장 먼저 할 ‘이것’", category: "EXPERIMENTAL" },
    { text: "과거로 돌아가도 다시 선택할 {topic} {number}가지", category: "EXPERIMENTAL" },
    { text: "내가 {topic} 하고 후회하는 것", category: "EXPERIMENTAL" },
    { text: "내가 {topic} 하고 180도 달라진 이유", category: "EXPERIMENTAL" },
    { text: "{number}개월 만에 {benefit} 달성한 비법", category: "EXPERIMENTAL" },
    { text: "{number}개월만에 {topic} 하고 느낀점", category: "EXPERIMENTAL" },
    { text: "{topic}에 {number}년 미쳐보니 느낀점", category: "EXPERIMENTAL" },
    { text: "{topic}에 {number}년 미쳐보고 달라진 점", category: "EXPERIMENTAL" },
    { text: "{topic} 하다 현타올 때 BEST {number}", category: "EXPERIMENTAL" },
    { text: "내가 {topic} 미친듯이 하고 나서 알게 된 {number}가지", category: "EXPERIMENTAL" },
    { text: "내가 {topic} 미친듯이 하고 나서 후회하는 {number}가지", category: "EXPERIMENTAL" },
    { text: "{topic} 했더니 결국..", category: "EXPERIMENTAL" },
    { text: "{topic} 해보니..", category: "EXPERIMENTAL" },
    { text: "내가 {topic} 할 수 있었던 진짜 이유", category: "EXPERIMENTAL" },
    { text: "내가 매일 {topic} 하는 진짜 이유", category: "EXPERIMENTAL" },
    { text: "내가 {benefit} 달성한 비법", category: "EXPERIMENTAL" },
    { text: "나를 변하게 해준 {topic} {number}단계", category: "EXPERIMENTAL" },
    { text: "나를 180도 변하게 해준 {topic}", category: "EXPERIMENTAL" },
    { text: "내가 180도 변하게 된 진짜 이유", category: "EXPERIMENTAL" },
    { text: "{topic} 바닥에서 {number}년만에 {benefit} 된 썰", category: "EXPERIMENTAL" },

    // 3. COMPARATIVE (Secret/Insight/Commonality focus)
    { text: "1억 {topic} VS 1만원 {topic}", category: "COMPARATIVE" },
    { text: "우리나라 사람들은 잘 모르는 {topic}의 비밀", category: "COMPARATIVE" },
    { text: "의외로 사람들이 모른다는 {topic} {number}가지", category: "COMPARATIVE" },
    { text: "{topic}으로 소문난 {authority} BEST {number}", category: "COMPARATIVE" },
    { text: "{authority}만이 알고 있는 {topic} 비법", category: "COMPARATIVE" },
    { text: "{authority}는 절대로 하지 않는 {number}가지", category: "COMPARATIVE" },
    { text: "{authority}도 몰래 쓰는 {topic}", category: "COMPARATIVE" },
    { text: "{authority}도 매일 한다는 {topic} {number}가지", category: "COMPARATIVE" },
    { text: "{topic} 성공하는 사람들의 비밀", category: "COMPARATIVE" },
    { text: "{topic} 성공한 사람만 안다는 {number}가지", category: "COMPARATIVE" },
    { text: "{topic} 고수들은 목숨걸고 지킨다는 {number}가지", category: "COMPARATIVE" },
    { text: "과거로 돌아간다면 절대 하지 않을 {topic} {number}가지", category: "COMPARATIVE" },
    { text: "{topic} 이후 더 {benefit} 하는 사람들의 공통점", category: "COMPARATIVE" },
    { text: "{topic} 한다면 {target}이 진짜 중요한 이유", category: "COMPARATIVE" },
    { text: "요즘 대세, {topic} 하는 비법", category: "COMPARATIVE" },
    { text: "요즘 {authority}들이 한다는 {topic} 방법", category: "COMPARATIVE" },
    { text: "{topic} 못하는 사람들의 특징", category: "COMPARATIVE" },
    { text: "{topic} 잘하는 사람들의 특징", category: "COMPARATIVE" },
    { text: "99.9% {topic} 실패하는 사람들의 특징", category: "COMPARATIVE" },
    { text: "{topic}해도 {benefit}하는 방법 (반전)", category: "COMPARATIVE" },

    // 4. AGGRESSIVE (How-to/Benefit/Solution focus)
    { text: "{topic}한다면 이제 더 이상 {benefit} 놓치지마세요", category: "AGGRESSIVE" },
    { text: "누구나 쉽게 따라하는 {topic} 하는 법", category: "AGGRESSIVE" },
    { text: "경력 {number}년차 {authority}가 말하는 {topic}", category: "AGGRESSIVE" },
    { text: "{authority}가 알려주는 {topic}하는 법", category: "AGGRESSIVE" },
    { text: "{benefit}하려면 지금 당장 시작해야 할 {number}가지 습관", category: "AGGRESSIVE" },
    { text: "세상에서 가장 간단한 {topic} 공식", category: "AGGRESSIVE" },
    { text: "한번쯤 알아두면 무조건 도움되는 {topic}", category: "AGGRESSIVE" },
    { text: "{topic}로 {benefit}할 수 있는 가장 쉬운 방법", category: "AGGRESSIVE" },
    { text: "{benefit} 할 수 있는 가장 쉬운 방법", category: "AGGRESSIVE" },
    { text: "{topic} 문제 해결하는 가장 간단한 방법", category: "AGGRESSIVE" },
    { text: "하루 {number}분만 따라해도 {benefit}할 수 있는 방법", category: "AGGRESSIVE" },
    { text: "이거 하나만 해도 {topic} 달라집니다", category: "AGGRESSIVE" },
    { text: "지금부터 꼭 해야할 {topic}", category: "AGGRESSIVE" },
    { text: "{topic} 하나로 {benefit}한 방법 {number}가지", category: "AGGRESSIVE" },
    { text: "{topic} 템플릿 무료배포", category: "AGGRESSIVE" },
    { text: "{benefit} 할 수 있는 무료 사이트 {number}개", category: "AGGRESSIVE" },
    { text: "{target}라면 꼭 알아야 할 사이트 {number}개", category: "AGGRESSIVE" },
    { text: "대부분이 사람들이 잘 모르는 {topic} 하는 법", category: "AGGRESSIVE" },
    { text: "{number}분만에 {topic} 끝내는 꿀팁", category: "AGGRESSIVE" },
    { text: "{benefit}하고 싶은 사람만 보세요", category: "AGGRESSIVE" },
    { text: "{target}은 무조건 봐야할 영상", category: "AGGRESSIVE" },
    { text: "나만 알고 싶은 {topic} 꿀팁", category: "AGGRESSIVE" },
    { text: "{topic} 할 때 {benefit} 해주는 가장 확실한 방법", category: "AGGRESSIVE" },
    { text: "{benefit} 만들어준 {topic} 비법", category: "AGGRESSIVE" },
    { text: "{topic}로 {benefit} 고민 해결하는 {number}가지 방법", category: "AGGRESSIVE" },
    { text: "{topic} 할 때 {number}초만에 해결하는 법", category: "AGGRESSIVE" },
];
